version: '3.8'

x-environment-vars: &environment-vars
  TERM: linux

services:
  module_b:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: worldskills_module_b
    env_file: .env
    environment:
      <<: *environment-vars
    volumes:
      - .:/proj
    command: npm run serve
    stdin_open: true
    tty: true
